<?php
include 'Template/layout/header.phtml';
?> 
<h1>AGREGAR UN PRODUCTO</h1>

<?php if (isset($mensaje)): ?>
    <p><?= htmlspecialchars($mensaje); ?></p>
<?php endif; ?>
<form action="add" method="POST" enctype="multipart/form-data">
    <input type="text" name="Nombre_producto" placeholder="Nombre del producto" required>

    <label for="id_proveedor">Selecciona un proveedor:</label>
    <select name="id_proveedor_fk" id="id_proveedor_fk" required> 
        <option value="">Seleccione un proveedor</option>
        <?php if (!empty($suppliers)): ?>
            <?php foreach ($suppliers as $supplier): ?>
                <option value="<?= $supplier->id_proveedor; ?>"><?= $supplier->Nombre_proveedor; ?></option>
            <?php endforeach; ?>
        <?php else: ?>
            <option value="">No hay proveedores disponibles</option>
        <?php endif; ?>
    </select>

    <input type="text" name="categoria" placeholder="Categoría" required>
    <input type="number" name="cantidad" placeholder="Cantidad" required>
    <input type="text" name="talle" placeholder="Talle" required>
    <input type="number" name="valor" placeholder="Valor" required>
    <input type="file" name="imagen" required>
  
    <input type="submit" value="Agregar producto">
</form>


<?php
include 'Template/layout/footer.phtml';
?>
