<?php include 'Template/layout/header.phtml'; ?>

<div>
<form action="addSupplier" method="POST">
        <input type="text" name="Nombre_proveedor" placeholder="Nombre del proovedor">
        <input type="text" name="medio_de_pago" placeholder="Medio de pago" >
        <input type="number" name="telefono" placeholder="Número de telefono">

        <input type="submit" value="Agregar proovedor">
    </form>
</div>

<?php include 'Template/layout/footer.phtml'; ?>
